<a href="https://colab.research.google.com/github/Aksuya/InteligenciaArtificial/blob/main/Lunes01_Julio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as algebraLineal


a = algebraLineal.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[:2])
print(a[1:3])


a[1]=88
print(a)


(3,)
<class 'numpy.ndarray'>
[11 22 33]
[11 22]
[22 33]
[11 88 33]


In [40]:
from re import sub
#dos dimensiones

import numpy as np

b=np.array([[1,2,3],[11,22,33], [111,222,333]])
print(b.shape)
print(type(b))
print(b)

print(b[1,1])

submatriz = b[1:3, 1:3].copy()
print(submatriz.shape)
print("antes")
print(submatriz)

submatriz[1]=88
print("despues")
print(submatriz)
print(b)



(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
(2, 2)
antes
[[ 22  33]
 [222 333]]
despues
[[22 33]
 [88 88]]
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]


In [42]:
#matriz de dos dimensiones con el modulo zero
import numpy as np

c=np.zeros((4,4))
print(c)
print(c.shape)
d=np.full((4,4),9)
print(d)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [45]:
#matriz con la diagonal que tenga como elemento la unidad

e=np.eye(3,3)
print(e)

f=np.ones((4,5))
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [48]:
g=np.random.random((5,5))
print(g)

#crear una matriz aleatoria que solo contenga elementos enteros, sea de 4x3 y que contenga solo numeros hasta el 20

matriz_aleatoria = np.random.randint(1, 21, size=(4, 3))
print(matriz_aleatoria)

[[0.81182233 0.40386305 0.64400644 0.61884935 0.83605565]
 [0.35315838 0.40822457 0.39924592 0.25205013 0.29873991]
 [0.3369747  0.48174055 0.01928524 0.52648824 0.29222692]
 [0.15226414 0.01641039 0.58324888 0.6585757  0.52556635]
 [0.70235012 0.39173836 0.24776439 0.09838007 0.70546413]]
[[17 14 16]
 [ 8 20  2]
 [ 7 13 12]
 [ 3 12 20]]


In [58]:
tmp1=np.random.randint(1,20, (4,4))
print(tmp1)

rows=np.array([0,1,2,0])
cols=np.arange(4)

print(rows)
print(cols)



[[ 3 14 16 14]
 [16  5  7 14]
 [14  5  6 19]
 [14  6 17  1]]
[0 1 2 0]
[0 1 2 3]


In [57]:
tmp1[rows, cols]=100
print(tmp1)


[[100   5  19 100]
 [ 15 100  12   2]
 [ 12   2 100   4]
 [ 11  12   9   5]]


In [60]:
#Matriz aleatoria de 6x6 pero que los elementos sean del 20 al 50


tmp1=np.random.randint(20,50, (6,6))
print(tmp1)


[[26 43 35 47 42 43]
 [40 42 42 27 44 26]
 [30 42 27 21 24 31]
 [27 49 48 27 31 49]
 [48 46 49 47 31 40]
 [40 35 32 36 42 49]]


In [67]:

filter = (tmp1 > 45)
print(filter)
print(tmp1[filter])



[[False False False  True False False]
 [False False False False False False]
 [False False False False False False]
 [False  True  True False False  True]
 [ True  True  True  True False False]
 [False False False False False  True]]
[47 49 48 49 48 46 49 47 49]


In [69]:
#imprimir los números pares, los rangos pueden ser del 1 al 100

tmp1=np.random.randint(1,100, (10,10))
print(tmp1)

[[ 4 28 76 53 97 98 44 33 55 21]
 [91 81 80 79 63 93 82 83 27 85]
 [80 42  4 26 54 84  1 95 62 74]
 [40 28 10 40 91 74 18 44  5 53]
 [65 20 63 62 38 66  4 49 89 87]
 [14 50 16 21 25 57 16 78 94 35]
 [79 47 44 83 90 93 50 90 96 67]
 [98 37 63 81 76 36 35 19 17 52]
 [18 22 76 18 25 91 98 95 19 74]
 [87 19 99 29 29  8 69  6 41 94]]


In [72]:
filter = (tmp1%2==0)
print(filter)
print(tmp1[filter])

[[ True  True  True False False  True  True False False False]
 [False False  True False False False  True False False False]
 [ True  True  True  True  True  True False False  True  True]
 [ True  True  True  True False  True  True  True False False]
 [False  True False  True  True  True  True False False False]
 [ True  True  True False False False  True  True  True False]
 [False False  True False  True False  True  True  True False]
 [ True False False False  True  True False False False  True]
 [ True  True  True  True False False  True False False  True]
 [False False False False False  True False  True False  True]]
[ 4 28 76 98 44 80 82 80 42  4 26 54 84 62 74 40 28 10 40 74 18 44 20 62
 38 66  4 14 50 16 16 78 94 44 90 50 90 96 98 76 36 52 18 22 76 18 98 74
  8  6 94]


In [77]:
tmp3 = np.array([1,2,3,4,5],dtype=np.float64)
print(tmp3.dtype)

float64


In [88]:
x=np.array([[1,2],[11,22]])
y=np.array([[22,33],[44,55]])
print(x)
print(y)

print("La suma")
print(np.add(x,y))
print("La resta")
print(np.subtract(x,y))
print("multiplicación")
print(np.multiply(x,y))
print("División")
print(np.divide(x,y))
print("raiz cuadrada")
print(np.sqrt(x))

[[ 1  2]
 [11 22]]
[[22 33]
 [44 55]]
La suma
[[23 35]
 [55 77]]
La resta
[[-21 -31]
 [-33 -33]]
multiplicación
[[  22   66]
 [ 484 1210]]
División
[[0.04545455 0.06060606]
 [0.25       0.4       ]]
raiz cuadrada
[[1.         1.41421356]
 [3.31662479 4.69041576]]


In [91]:
tmp1=np.random.randint(1,10, (2,5))
print(tmp1)
#promedio
aux = tmp1.mean()
print(aux)

[[6 5 9 9 1]
 [6 2 4 5 9]]
5.6


In [93]:
print(tmp1.mean(axis=1))
print(tmp1.mean(axis=0))

[6.  5.2]
[6.  3.5 6.5 7.  5. ]
